# Generated by Django 2.2.5 on 2019-09-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='member',
            field=models.ManyToManyField(to='contacts.Person'),
        ),
    ]
